# Generated by Django 5.2.3 on 2025-07-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='text',
        ),
    ]
